

select * from detalhe_fornecedor
select * from fornecendo
select * from pedindo


SELECT
	PR.ID AS ID,
	PR.NOME AS NOME,
	PR.VALOR AS VALOR,
	PR.DESCRICAO AS DESCRICAO,
	F.QUANTIDADE AS TEM
FROM
	FORNECENDO AS F
INNER JOIN
	PRODUTO AS PR
ON
	PR.ID = F.ID_PRODUTO
WHERE
	F.FINALIZADO = 'SIM'
AND
	F.ID_DETALHE = 4

/* SELECT PEDINDO */
SELECT
	COUNT(*) as NUMERO,
	SUM(P.VALOR * PE.QUANTIDADE) AS VALOR
FROM
	PEDINDO AS PE
INNER JOIN
	PRODUTO AS P
ON
	P.ID = PE.ID_PRODUTO
WHERE
	PE.FINALIZADO = 'SIM'
AND
	PE.ID_DETALHE = 46;

/* SELECT FORNECENDO */
SELECT
	COUNT(*) as NUMERO,
	SUM(P.VALOR * F.QUANTIDADE) AS VALOR
FROM
	FORNECENDO AS F
INNER JOIN
	PRODUTO AS P
ON
	P.ID = F.ID_PRODUTO
WHERE
	F.FINALIZADO = 'SIM'
AND
	F.ID_DETALHE = 4

/* SELECTs*/
SELECT * FROM PEDINDO
SELECT * FROM PEDINDO WHERE ID_CLIENTE = 14
SELECT * FROM FORNECENDO
DELETE FROM PRODUTO AS a INNER JOIN PRODUTO AS b ON a.nome=b.nome WHERE a.id < b.id
SELECT * FROM PRODUTO AS a INNER JOIN PRODUTO AS b ON a.nome=b.nome WHERE a.id < b.id
SELECT * FROM PRODUTO ORDER BY NOME

truncate pedindo;
truncate FORNECENDO;
truncate detalhe_fornecedor;
truncate detalhe_pedido;

select * from FORNECENDO


DELETE FROM PRODUTO WHERE ID NOT IN (418,80,411,78,416,417,419,34,7,415,143)



SELECT COUNT(*) as NUMERO, SUM(P.VALOR * F.QUANTIDADE) AS VALOR FROM FORNECENDO AS F INNER JOIN PRODUTO AS P ON P.ID = F.ID_PRODUTO WHERE F.FINALIZADO = 'SIM' AND F.ID_DETALHE =46



SELECT COUNT(*) as NUMERO, SUM(P.VALOR * F.QUANTIDADE) AS VALOR FROM FORNECENDO AS F INNER JOIN PRODUTO AS P ON P.ID = F.ID_PRODUTO WHERE F.FINALIZADO = 'SIM' AND F.ID_DETALHE =4
