CREATE TABLE COMUNICADO(
	ID SERIAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID) ON DELETE CASCADE
)

SELECT * FROM COMUNICADO

SELECT * FROM MENSAGEM


SELECT PR.ID, PR.NOME AS NOME, PR.VALOR AS VALOR, SUM(P.QUANTIDADE) AS QUANTIDADE, SUM(PR.VALOR * P.QUANTIDADE) AS VALOR_TOTAL FROM FORNECENDO AS P
								INNER JOIN PRODUTO AS PR ON PR.ID = P.ID_PRODUTO
								INNER JOIN FORNECEDOR AS C ON P.ID_FORNECEDOR = C.ID
								WHERE C.ID = 7
								GROUP BY PR.NOME, PR.VALOR, PR.ID