CREATE TYPE LIDA AS ENUM('SIM', 'NÃO')
drop type LIDA


CREATE TABLE ASSUNTO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ID_RECEBENDO INT NOT NULL,
	ID_ENVIANDO INT NOT NULL,
	MENSAGEM VARCHAR(255) NOT NULL,

	FOREIGN KEY(ID_RECEBENDO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_ENVIANDO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
	PRIMARY KEY(ID)
)
drop table assunto

CREATE TABLE ENTRADAMENSAGEM(
	ID SERIAL NOT NULL,
	ASSUNTO INT not null,
	ENVIADO_POR INT NOT NULL,
	MENSAGEM VARCHAR(255) NOT NULL,
	LIDA LIDA DEFAULT 'NÃO',

	PRIMARY KEY(ID),
	FOREIGN KEY(ASSUNTO) REFERENCES ASSUNTO(ID) ON DELETE CASCADE
);

DROP TABLE ENTRADAMENSAGEM
truncate ENTRADAMENSAGEM
SELECT * FROM USUARIO

INSERT INTO ENTRADAMENSAGEM (ID_RECEBENDO, ID_ENVIANDO, ASSUNTO, MENSAGEM) VALUES (1, 2,, :assunto, :mensagem)
INSERT INTO ENTRADAMENSAGEM (ID_RECEBENDO, ID_ENVIANDO, ASSUNTO, MENSAGEM) VALUES ()

select * from entradamensagem 
select * from assunto

SELECT
	E.ID AS ID,
	U.NOME AS RECEBENDO,
	S.NOME AS ENVIANDO,
	E.ASSUNTO AS ASSUNTO,
	E.MENSAGEM AS MENSAGEM,
	E.LIDA AS LIDA
FROM
	ENTRADAMENSAGEM AS E
INNER JOIN
	USUARIO AS U
ON
	E.ID_RECEBENDO = U.ID
INNER JOIN
	USUARIO AS S
ON
	E.ID_ENVIANDO = S.ID


UPDATE ENTRADAMENSAGEM SET MENSAGEM = CONCAT(MENSAGEM, '&&ENDTeste tres!') WHERE ID = 1

/* ALTERAÇÃO PARA MUDAR EM TODOS */
ALTER TABLE ENTRADAMENSAGEM ALTER COLUMN MENSAGEM TYPE VARCHAR(1000);

ID_RECEBENDO
ID_CLIENTE
ASSUNTO
MENSAGEM
LIDA

select * from ENTRADAMENSAGEM 

SELECT
	A.ID AS ID,
	U.NOME AS RECEBENDO,
	S.NOME AS ENVIANDO,
	A.NOME AS ASSUNTO,
	E.MENSAGEM AS MENSAGEM,
	E.LIDA AS LIDA
FROM
	ASSUNTO AS A
INNER JOIN
	USUARIO AS U
ON
	A.ID_RECEBENDO = U.ID
INNER JOIN
	USUARIO AS S
ON
	A.ID_ENVIANDO = S.ID
INNER JOIN
	ENTRADAMENSAGEM AS E
ON
	E.ASSUNTO = A.ID


SELECT
	E.ID AS ID,
	U.NOME AS RECEBENDO,
	S.NOME AS ENVIANDO,
	E.ASSUNTO AS ASSUNTO,
	E.MENSAGEM AS MENSAGEM,
	E.LIDA AS LIDA
FROM
	ASSUNTO AS A
INNER JOIN
	ENTRADAMENSAGEM AS E
ON
	E.ASSUNTO = A.ID
INNER JOIN
	USUARIO AS U
ON
	A.ID_RECEBENDO = U.ID
INNER JOIN
	USUARIO AS S
ON
	A.ID_ENVIANDO = S.ID
WHERE E.ASSUNTO = 1