CREATE TABLE MENSAGEM(
	ID SERIAL NOT NULL,
	ASSUNTO VARCHAR(15) NOT NULL,
	DESCRICAO INT NOT NULL,
	DATA_MSG DATE NOT NULL,
	ID_DE INT NOT NULL,
	DE VARCHAR(30) NOT NULL,
	LIDA LIDA DEFAULT 'NAO',

	PRIMARY KEY(ID),
	FOREIGN KEY(DESCRICAO) REFERENCES TIPO_MENSAGEM(ID) ON DELETE CASCADE
);
DROP TABLE MENSAGEM;
TRUNCATE MENSAGEM

SELECT ID, ASSUNTO, DESCRICAO, DATA_MSG, ID_DE FROM MENSAGEM
SELECT ID, ASSUNTO, DESCRICAO, to_char(DATA_MSG, 'DD/MM/YYYY'), ID_DE, LIDA FROM MENSAGEM

INSERT INTO MENSAGEM (ASSUNTO, DESCRICAO, DATA_MSG, ID_DE, DE) VALUES ('Teste', 1, NOW(), 3, 'Tuta');
INSERT INTO MENSAGEM (ASSUNTO, DESCRICAO, DATA_MSG, ID_DE, DE) VALUES ('Cliente', 2, NOW(), 4, 'Fernando');

SELECT COUNT(LIDA) AS LIDA FROM MENSAGEM WHERE LIDA = 'NAO'

CREATE TYPE LIDA AS ENUM('SIM', 'NAO');
DROP TYPE LIDA

ALTER TABLE MENSAGEM
ADD COLUMN LIDA LIDA NOT NULL DEFAULT 'NAO';

ALTER TABLE MENSAGEM
ADD COLUMN DE varchar(30) not null;



SELECT * FROM MENSAGEM
SELECT * FROM TIPO_MENSAGEM
SELECT ID, ASSUNTO, DESCRICAO, DATA_MSG, ID_DE FROM MENSAGEM


CREATE TABLE TIPO_MENSAGEM(
	ID INT NOT NULL,
	DESCRICAO VARCHAR(255),

	PRIMARY KEY(ID)
)
DROP TABLE TIPO_MENSAGEM

INSERT INTO TIPO_MENSAGEM (ID, DESCRICAO) VALUES (1, 'Atingiu a quantidade mínima');
INSERT INTO TIPO_MENSAGEM (ID, DESCRICAO) VALUES (2, 'Cliente pagamento VENCIDO');
INSERT INTO TIPO_MENSAGEM (ID, DESCRICAO) VALUES (3, 'Produto já saiu?');
INSERT INTO TIPO_MENSAGEM (ID, DESCRICAO) VALUES (4, 'Produto já chegou?');
INSERT INTO TIPO_MENSAGEM (ID, DESCRICAO) VALUES (5, 'Cliente não compra mais de 2 meses');


SELECT
	P.ID, P.NOME,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = P.ID AND M.DE = 'PRODUTO' AND ID_DE = P.ID AND M.DESCRICAO = 1) AS JA
FROM
	PRODUTO AS P
WHERE P.QUANTIDADE < P.MINIMO


SELECT
	P.ID, P.NOME
FROM
	PRODUTO AS P, MENSAGEM AS M
WHERE P.QUANTIDADE < P.MINIMO AND M.ID_DE != P.ID AND M.DE != 'PRODUTO' AND ID_DE != P.ID AND M.DESCRICAO != 1



