/*	SE O PRODUTO CHEGOU NO MINIMO	*/
SELECT
	P.ID, P.NOME,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = P.ID AND M.DE = 'PRODUTO' AND ID_DE = P.ID AND M.DESCRICAO = 1) AS JA
FROM
	PRODUTO AS P
WHERE P.QUANTIDADE < P.MINIMO




/*	SE O CLIENTE COM VENCIMENTO DE PAGAMENTO E ENTREGA DE PRODUTO	*/
SELECT
	C.NOME AS NOME,
	C.ID AS ID,
	D.ENTREGUE AS ENTREGUE,
	D.STATUS AS STATUS,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = C.ID AND M.DE = 'CLIENTE' AND ID_DE = C.ID AND M.DESCRICAO = 2) AS JAVENCIDO,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = C.ID AND M.DE = 'CLIENTE' AND ID_DE = C.ID AND M.DESCRICAO = 3) AS JASAIU
FROM
	DETALHE_PEDIDO AS D
INNER JOIN
	CLIENTE AS C
ON
	D.ID_CLIENTE = C.ID
WHERE
	D.VENCIMENTO < NOW()




/*	SELECIONA TODOS OS PEDIDOS	*/
SELECT * FROM DETALHE_PEDIDO




/*	CHEGOU PRODUTO?	*/
SELECT
	F.NOME,
	F.ID,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = F.ID AND M.DE = 'FORNECEDOR' AND ID_DE = F.ID AND M.DESCRICAO = 4) AS JA
FROM
	DETALHE_FORNECEDOR AS D
INNER JOIN
	FORNECEDOR AS F
ON
	D.ID_FORNECEDOR = F.ID
WHERE
	VENCIMENTO < NOW()




/*	SE O CLIENTE NÃO COMPROU A 2 MESES	*/
SELECT
	NOME,
	ID,
	(SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = C.ID AND M.DE = 'CLIENTE' AND ID_DE = C.ID AND M.DESCRICAO = 5) AS JA
FROM
	CLIENTE AS C
WHERE
	C.DATA_ULTIMA_COMPRA < NOW() - INTERVAL '2' MONTH




SELECT COUNT(*) FROM MENSAGEM AS M WHERE M.ID_DE = C.ID AND M.DE = 'CLIENTE' AND ID_DE = C.ID AND M.DESCRICAO = 2




