CREATE TABLE PRODUTO(
	ID SERIAL NOT NULL,
	NRO VARCHAR(40),
	NOME VARCHAR(30) NOT NULL,
	ID_CATEGORIA INT,
	VALOR DECIMAL(10,2),
	DESCRICAO VARCHAR(255),
	MINIMO INT,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	ID SERIAL NOT NULL,
	DATA_ULTIMA_COMPRA DATE,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ NUMERIC,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE NUMERIC,
	PRIMARY KEY(ID)
);

CREATE TABLE FORNECEDOR(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ NUMERIC,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE NUMERIC,
	PRIMARY KEY(ID)
);

CREATE TABLE DETALHE_PEDIDO(
	ID SERIAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,
	VENCIMENTO DATE,
	STATUS ESCOLHA,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE DETALHE_FORNECEDOR(
	ID SERIAL NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,
	VENCIMENTO DATE,
	STATUS ESCOLHA,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID) ON DELETE CASCADE
);

CREATE TABLE FORNECENDOR(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);

CREATE TABLE PEDINDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);


DROP TABLE PEDINDO;
DROP TABLE FORNECENDOR;
DROP TABLE DETALHE_FORNECEDOR;
DROP TABLE DETALHE_PEDIDO;
DROP TABLE FORNECEDOR;
DROP TABLE CLIENTE;
DROP TABLE PRODUTO;

SELECT * FROM PEDINDO;
SELECT * FROM FORNECENDOR;
SELECT * FROM DETALHE_FORNECEDOR;
SELECT * FROM DETALHE_PEDIDO;
SELECT * FROM FORNECEDOR;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

TRUNCATE PEDINDO;
TRUNCATE FORNECENDOR;
TRUNCATE DETALHE_FORNECEDOR;
TRUNCATE DETALHE_PEDIDO;
TRUNCATE FORNECEDOR;
TRUNCATE CLIENTE;
TRUNCATE PRODUTO;
