CREATE TABLE PRODUTO(
	ID SERIAL NOT NULL,
	NRO VARCHAR(40),
	NOME VARCHAR(30) NOT NULL,
	ID_CATEGORIA INT,
	VALOR DECIMAL(10,2),
	DESCRICAO VARCHAR(255),
	MINIMO INT,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	ID SERIAL NOT NULL,
	DATA_ULTIMA_COMPRA DATE,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ NUMERIC,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE NUMERIC,
	PRIMARY KEY(ID)
);

CREATE TABLE FORNECEDOR(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ NUMERIC,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE NUMERIC,
	PRIMARY KEY(ID)
);

CREATE TABLE DETALHE_PEDIDO(
	ID SERIAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,
	VENCIMENTO DATE,
	STATUS ESCOLHA,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES PEDINDO(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE DETALHE_FORNECEDOR(
	ID SERIAL NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,
	VENCIMENTO DATE,
	STATUS ESCOLHA,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECENDO(ID_FORNECEDOR) ON DELETE CASCADE
);

CREATE TABLE FORNECENDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);

CREATE TABLE PEDINDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);

INSERT INTO PEDINDO (ID_PRODUTO, ID_CLIENTE, QUANTIDADE) VALUES (2, 2, 3);
INSERT INTO PEDINDO (ID_PRODUTO, ID_CLIENTE, QUANTIDADE) VALUES (7, 1, 1);

SELECT P.ID, PR.NOME, C.EMPRESA, PR.VALOR, P.QUANTIDADE, (PR.VALOR * P.QUANTIDADE) AS VALOR FROM PEDINDO AS P 
INNER JOIN PRODUTO AS PR ON P.ID_PRODUTO = PR.ID
INNER JOIN CLIENTE C ON P.ID_CLIENTE = C.ID

DROP TABLE PEDINDO;
DROP TABLE FORNECEDOR;
DROP TABLE DETALHE_FORNECEDOR;
DROP TABLE DETALHE_PEDIDO;
DROP TABLE FORNECEDOR;
DROP TABLE CLIENTE;
DROP TABLE PRODUTO;

SELECT * FROM PEDINDO;
SELECT * FROM FORNECEDOR;
SELECT * FROM DETALHE_FORNECEDOR;
SELECT * FROM DETALHE_PEDIDO;
SELECT * FROM FORNECEDOR;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

TRUNCATE PEDINDO;
TRUNCATE FORNECENDOR;
TRUNCATE DETALHE_FORNECEDOR;
TRUNCATE DETALHE_PEDIDO;
TRUNCATE FORNECEDOR;
TRUNCATE CLIENTE;
TRUNCATE PRODUTO;
