CREATE TYPE FINALIZADO AS ENUM('SIM', 'NAO');
DROP TYPE FINALIZADO

-- TABELA FORNECENDO --
CREATE TABLE FORNECENDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PEDIDO) REFERENCES DETALHE_PEDIDO(ID) ON DELETE CASCADE
);
DROP TABLE FORNECENDO

SELECT * FROM FORNECENDO WHERE ID_FORNECEDOR = 1

ALTER TABLE FORNECENDO
ADD COLUMN FINALIZADO FINALIZADO NOT NULL DEFAULT 'NAO';


-- TABELA PEDINDO --
CREATE TABLE PEDINDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PEDIDO) REFERENCES DETALHE_PEDIDO(ID) ON DELETE CASCADE
);
DROP TABLE PEDINDO

SELECT * FROM PEDINDO WHERE ID_CLIENTE = 1


ALTER TABLE PEDINDO
ADD COLUMN FINALIZADO FINALIZADO NOT NULL DEFAULT 'NAO';

