-- TABELA CATEGORIA --
CREATE TABLE CATEGORIA(
	ID SERIAL NOT NULL,
	NOME VARCHAR(20),

	PRIMARY KEY(ID)
);
DROP TABLE CATEGORIA;
SELECT * FROM CATEGORIA;
DELETE FROM CATEGORIA WHERE ID = 2369

INSERT INTO CATEGORIA (NOME) VALUES ('TUBO');
INSERT INTO CATEGORIA (NOME) VALUES ('LIXEIRA');
INSERT INTO CATEGORIA (NOME) VALUES ('SUPORTE');
INSERT INTO CATEGORIA (NOME) VALUES ('AVIAMENTO');
INSERT INTO CATEGORIA (NOME) VALUES ('ELETRONICO');
INSERT INTO CATEGORIA (NOME) VALUES ('MOVEIS');

UPDATE CATEGORIA SET NOME = 'tubo' WHERE NOME = 'TUBO';
UPDATE CATEGORIA SET NOME = 'lixeira' WHERE NOME = 'LIXEIRA';
UPDATE CATEGORIA SET NOME = 'suporte' WHERE NOME = 'SUPORTE';
UPDATE CATEGORIA SET NOME = 'aviamento' WHERE NOME = 'AVIAMENTO';
UPDATE CATEGORIA SET NOME = 'eletronico' WHERE NOME = 'ELETRONICO';
UPDATE CATEGORIA SET NOME = 'moveis' WHERE NOME = 'MOVEIS';
UPDATE CATEGORIA SET NOME = 'escolar' WHERE NOME = 'ESCOLA';

-- TABELA PRODUTOS --
CREATE TABLE PRODUTO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ID_CATEGORIA INT,
	VALOR DECIMAL(10,2),
	DESCRICAO VARCHAR(255),
	MINIMO INT,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);
DROP TABLE PRODUTO;
SELECT * FROM PRODUTO;
DELETE FROM PRODUTO WHERE ID = 2369

INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('PC', 5, 2200.99, 'DELL TESTE, I7, 2T, 16GB', 100, 80);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('FERRO', 5, 122.99, 'FERRO FERE QUALQUER UM', 10, 2);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('NOTEBOOK', 5, 2200.99, 'VAIO C14, I5, 1T, 8GB', 10, 100);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CAMA', 6, 1000.00, 'CAMA BOX COM COLCHÃO E CABECEIRA', 5, 34);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CANO', 1, 10, 'CANO PVC PARA ESGOTO', 30, 100);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('LIXEIRA', 2, 200.59, 'LIXEIRA COM PÉ PARA ALTARA', 4, 23);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('TECIDO', 4, 20, 'TECIDO FINO CARA DE RICA', 10, 200);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CELULAR', 5, 2000, 'CELULAR TOP DE LINHA', 10, 30);

UPDATE PRODUTO SET NOME = 'TESTE', ID_CATEGORIA = '4', VALOR = 1234, DESCRICAO = 'TESTE LOUCO', MINIMO = 10, QUANTIDADE = 300 WHERE ID = 2380

