CREATE TABLE CATEGORIA(
	ID SERIAL NOT NULL,
	NOME VARCHAR(20),

	PRIMARY KEY(ID)
);

CREATE TABLE PRODUTO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ID_CATEGORIA INT,
	VALOR DECIMAL(10,2),
	DESCRICAO VARCHAR(255),
	MINIMO INT,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ INT,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE INT,

	PRIMARY KEY(ID)
);

CREATE TABLE FORNECEDOR(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	EMPRESA VARCHAR(30),
	CNPJ INT,
	LOCALIDADE VARCHAR(255),
	EMAIL VARCHAR(50),
	TELEFONE INT,

	PRIMARY KEY(ID)
);

CREATE TABLE DETALHE_PEDIDO(
	ID SERIAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE DETALHE_FORNECEDOR(
	ID SERIAL NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TEMPO DATE,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID) ON DELETE CASCADE
);

CREATE TABLE FORNECENDOR(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PEDIDO) REFERENCES DETALHE_PEDIDO(ID) ON DELETE CASCADE
);

CREATE TABLE PEDINDO(
	ID SERIAL NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
	FOREIGN KEY(ID_PEDIDO) REFERENCES DETALHE_PEDIDO(ID) ON DELETE CASCADE
);

CREATE TABLE USUARIO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(40) NOT NULL,
	SENHA VARCHAR(40) NOT NULL,

	PRIMARY KEY(ID)
);

DROP TABLE USUARIO;

SELECT * FROM USUARIO;
DELETE FROM USUARIO WHERE id = 13;
UPDATE usuario SET nome = 'João',usuario = 'Joção', senha = MD5('joão') WHERE id = 12;
UPDATE usuario SET nome = 'Filipinas',usuario = 'Doidão', senha = MD5('açucar') WHERE id = 10;

INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Fernando', 'nando', MD5('123321'));
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Jaqueline', 'jaque', MD5('jaque'));
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Mel', 'mel', MD5('mel'));
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Livro', 'livro', MD5('livro'));
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Teste', 'teste', MD5('teste'));
INSERT INTO USUARIO (NOME, USUARIO, SENHA) VALUES ('Lindinalva', 'Lindi', MD5('nalva'));

INSERT INTO (NOME, ID_CATEGORIA, VALOR, DESCRICAO, MINIMO, QUANTIDADE) VALUES ()

INSERT INTO CATEGORIA (NOME) VALUES ('TUBO');
INSERT INTO CATEGORIA (NOME) VALUES ('LIXEIRA');
INSERT INTO CATEGORIA (NOME) VALUES ('SUPORTE');
INSERT INTO CATEGORIA (NOME) VALUES ('AVIAMENTO');
INSERT INTO CATEGORIA (NOME) VALUES ('ELETRONICO');
INSERT INTO CATEGORIA (NOME) VALUES ('MOVEIS');

SELECT * FROM CATEGORIA;
SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('NOTEBOOK', 5, 2200.99, 'VAIO C14, I5, 1T, 8GB', 10, 100);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CAMA', 6, 1000.00, 'CAMA BOX COM COLCHÃO E CABECEIRA', 5, 34);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CANO', 1, 10, 'CANO PVC PARA ESGOTO', 30, 100);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('LIXEIRA', 2, 200.59, 'LIXEIRA COM PÉ PARA ALTARA', 4, 23);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('TECIDO', 4, 20, 'TECIDO FINO CARA DE RICA', 10, 200);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('CELULAR', 5, 2000, 'CELULAR TOP DE LINHA', 10, 30);
INSERT INTO PRODUTO (NOME,ID_CATEGORIA,VALOR,DESCRICAO,MINIMO,QUANTIDADE) VALUES ('TECIDO', 10, 20, 'TECIDO FINO CARA DE RICA', 10, 200);

select p.nome, c.nome as categoria, p.valor, p.descricao from produto as p inner join categoria as c on p.id_categoria = c.id
