CREATE TABLE PROJETOS(
	ID SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	ENVOLVIDO INT NOT NULL,
	DETERMINADO DATE NOT NULL,

	PRIMARY KEY(ID)
);
DROP TABLE PROJETOS
SELECT * FROM PROJETOS

INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('GALPAO', 'AUMENTAR O GALPAO PARA MELHOR PRODUCAO', 12, '2019-03-25')
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('MESA', 'MESA MAIOR PARA OS FUNCIONARIOS', 1, '2019-12-25');
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('COMPUTADOR', 'DEIXAR O LOCAL DE TRABALHO MAIS FORTE EM TECNOLOGIA', 21, '2019-10-25');
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('ESCRITORIO', 'MUDAR O SETOR DE ESCRITORIO PARA OUTRO LADO', 16, '2019-04-25');
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('MARKETING', 'FAZER UM SITE MAIS ROBUSTO', 43, '2019-10-25');
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('VENDAS', 'DEIXAR QUE O SISTEMA VENDA SOZINHO', 4, '2020-01-25');
INSERT INTO PROJETOS (NOME, DESCRICAO, ENVOLVIDO, DETERMINADO) VALUES ('LOCAL', 'TRANSFERIR A EMPRESA PARA JOENVILE', 65, '2021-12-20');
