CREATE TYPE PLANOS AS ENUM('BÁSICO', 'INTERMEDIÁRIO', 'AVANÇADO', 'MODIFICADO');

CREATE TABLE USUARIO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(40) NOT NULL,
	SENHA VARCHAR(40) NOT NULL,
	ENDERECO VARCHAR(255),
	FANTASIA VARCHAR(60),
	TIPO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	PLANO PLANOS NOT NULL,

	PRIMARY KEY(ID)
);
DROP TABLE USUARIO;

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Fernando', 'fer@nando.com', 'nando', MD5('123321'), 'Rua jasim, Diadema, Serraria', 'FBO - TI', 1, 24.90, 'BÁSICO');

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Jaqueline', 'jaque@line.com', 'jaque', MD5('jaque'), 'Rua arthur pereira, 90', 'JaqueBelo', 1, 24.90, 'BÁSICO');

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Mel', 'mel@dog.com', 'mel', MD5('mel'), 'Rua piratininga 234, servinha de Deus', 'Mel', 1, 39.90, 'INTERMEDIÁRIO');

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Livro', 'livro@saraiva.com', 'livro', MD5('livro'), 'Rua saraiva, livraria', 'Saraiva', 3, 39.90, 'INTERMEDIÁRIO');

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Teste', 'teste@test.com', 'teste', MD5('teste'), 'Rua teste maria teste, 201', 'Teste', 2, 54.90, 'AVANÇADO');

INSERT INTO USUARIO 
	(NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO)
VALUES
	('Lindinalva', 'lindi@nalva.com', 'Lindinalva', MD5('nalva'), 'Rua Francisco pereira, 17', 'Lindi', 1, 54.90, 'AVANÇADO');



SELECT NOME, EMAIL, USUARIO, SENHA, ENDERECO, FANTASIA, TIPO, VALOR, PLANO FROM USUARIO WHERE USUARIO = 'teste'