/* COMANDOS NOVOS PARA SINTRONIZAÇÃO */
	TRUNCATE PEDINDO;
	TRUNCATE FORNECENDO;
	TRUNCATE DETALHE_FORNECEDOR;
	TRUNCATE DETALHE_PEDIDO;

	CREATE TYPE FINALIZADO AS ENUM('SIM', 'NAO');
	DROP TYPE FINALIZADO
	ALTER TABLE PEDINDO
	ADD COLUMN FINALIZADO FINALIZADO NOT NULL DEFAULT 'NAO';
	ALTER TABLE FORNECENDO
	ADD COLUMN FINALIZADO FINALIZADO NOT NULL DEFAULT 'NAO';

	ALTER TABLE PEDINDO
	ADD COLUMN ID_DETALHE INT;
	ALTER TABLE FORNECENDO
	ADD COLUMN ID_DETALHE INT;

	ALTER TABLE DETALHE_FORNECEDOR
	ADD COLUMN PRODUTOS VARCHAR(100) NOT NULL;
	ALTER TABLE DETALHE_PEDIDO
	ADD COLUMN PRODUTOS VARCHAR(100) NOT NULL;
	/* DELETANDO A TABELA */
	ALTER TABLE DETALHE_FORNECEDOR DROP PRODUTOS;
	ALTER TABLE DETALHE_PEDIDO DROP PRODUTOS;

	CREATE TABLE MENSAGEM(
		ID SERIAL NOT NULL,
		ASSUNTO VARCHAR(15) NOT NULL,
		DESCRICAO VARCHAR(255) NOT NULL,
		DATA_MSG DATE NOT NULL,
		ID_DE VARCHAR(20) NOT NULL,

		PRIMARY KEY(ID)
	);
	DROP TABLE MENSAGEM;

	SELECT ID, ASSUNTO, DESCRICAO, DATA_MSG, ID_DE FROM MENSAGEM
	SELECT ID, ASSUNTO, DESCRICAO, to_char(DATA_MSG, 'DD/MM/YYYY'), ID_DE FROM MENSAGEM

	INSERT INTO MENSAGEM (ASSUNTO, DESCRICAO, DATA_MSG, ID_DE) VALUES ('Cliente', 'Não compra mais de 3 meses', NOW(), 'Fernando')




