CREATE TYPE PLANOS AS ENUM('BÁSICO', 'INTERMEDIÁRIO', 'AVANÇADO', 'MODIFICADO');

CREATE TABLE TIPOS(
	ID SERIAL NOT NULL,
	NOME VARCHAR(100),
	ACESSO VARCHAR(100),

	PRIMARY KEY(ID)
)
DROP TABLE TIPOS

SELECT * FROM TIPOS where ID = 2
UPDATE TIPOS SET NOME = 'Master', ACESSO = '0' WHERE ID = 1

/*INSERT INTO TIPOS ('NOME', 'ACESSO') VALUES ('MASTER', '{10000, 10000, 10000, 10000}', '{{"meeting", "lunch"}, {"training", "presentation"}}');*/
INSERT INTO TIPOS (NOME, ACESSO) VALUES ('MASTER', '0');
INSERT INTO TIPOS (NOME, ACESSO) VALUES ('BASICO', '1/2/3/4/');


CREATE TABLE USUARIO(
	ID SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(40) NOT NULL,
	SENHA VARCHAR(40) NOT NULL,
	ID_TIPOS INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(ID_TIPOS) REFERENCES TIPOS(ID) ON DELETE CASCADE
);
DROP TABLE USUARIO;

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Fernando', 'fer@nando.com', 'nando', MD5('123321'), 1);

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Jaqueline', 'jaque@line.com', 'jaque', MD5('jaque'), 1);

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Mel', 'mel@dog.com', 'mel', MD5('mel'), 2);

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Livro', 'livro@saraiva.com', 'livro', MD5('livro'), 2);

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Teste', 'teste@test.com', 'teste', MD5('teste'), 2);

INSERT INTO USUARIO  (NOME, EMAIL, USUARIO, SENHA, ID_TIPOS)
VALUES ('Lindinalva', 'lindi@nalva.com', 'Lindinalva', MD5('nalva'), 2);



SELECT NOME, EMAIL, USUARIO, SENHA, TIPO FROM USUARIO WHERE USUARIO = 'teste'
SELECT U.NOME, U.EMAIL, U.USUARIO, T.NOME AS TIPO FROM USUARIO AS U INNER JOIN TIPOS AS T ON T.ID = U.ID_TIPOS

SELECT * FROM USUARIO
SELECT * FROM TIPOS

SELECT NOME, EMAIL, USUARIO, AS TIPO FROM USUARIO WHERE USUARIO = 'teste'

SELECT U.NOME AS NOME, U.EMAIL AS EMAIL, U.USUARIO AS USUARIO, T.NOME AS TIPO FROM USUARIO AS U INNER JOIN TIPOS AS T ON T.ID = U.ID_TIPOS
SELECT U.NOME AS NOME, U.EMAIL AS EMAIL, U.USUARIO AS USUARIO, T.ACESSO AS TIPO FROM USUARIO AS U INNER JOIN TIPOS AS T ON T.ID = U.ID_TIPOS WHERE U.ID
SELECT U.ID AS ID, U.NOME AS NOME, U.USUARIO AS USUARIO, T.ACESSO AS TIPO FROM USUARIO U INNER JOIN TIPOS AS T ON T.ID = U.ID_TIPOS WHERE U.USUARIO = 'nando' AND U.SENHA = MD5('123321')
SELECT T.ACESSO AS ACESSO FROM USUARIO AS U INNER JOIN TIPOS AS T ON T.ID = U.ID_TIPOS WHERE U.ID = 5

UPDATE USUARIO SET SENHA = MD5('123321') WHERE ID = 1